In [2]:
import pandas as pd
import numpy as np
from faker import Faker
from datetime import timedelta

In [3]:
fake = Faker()
np.random.seed(42)

num_rows = 150

##### *Customers Table*

In [4]:
customers = pd.DataFrame({
    "customer_id": range(1, num_rows + 1),
    "name": [fake.name() for _ in range(num_rows)],
    "email": [fake.email() for _ in range(num_rows)]
})

In [5]:
customers.head()

   customer_id               name                    email
0            1        Dawn Cooper  zacharyhill@example.net
1            2        Daniel Mann   greenmegan@example.org
2            3      Edward Harmon  mstrickland@example.org
3            4  Miss Monica Ramos   aaronowens@example.net
4            5   Charles Johnston       john91@example.net

In [12]:
customers.info()
orders.info()
shipments.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  150 non-null    int64
 1   name         150 non-null    str
 2   email        150 non-null    str
dtypes: int64(1), str(2)
memory usage: 3.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      150 non-null    int64
 1   customer_id   150 non-null    int64
 2   order_date    150 non-null    object
 3   order_amount  150 non-null    float64
 4   currency      150 non-null    str
dtypes: float64(1), int64(2), object(1), str(1)
memory usage: 6.0+ KB
<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   shipment_id   300 non-null    str
 1   order_id      300 non-null    int64
 2   status        300 non-null    str
 3   shipped_at    300 non-null    object
 4   delivered_at  151 non-null    object
dtypes: int64(1), object(2), str(2)
memory usage: 11.8+ KB

##### *Orders Table*

In [7]:
orders = pd.DataFrame({
    "order_id": range(1001, 1001 + num_rows),
    "customer_id": np.random.choice(customers["customer_id"], num_rows),
    "order_date": [fake.date_between(start_date="-1y", end_date="today") for _ in range(num_rows)],
    "order_amount": np.round(np.random.uniform(20, 500, num_rows), 2),
    "currency": ["USD"] * num_rows
})

In [31]:
orders.head()

   order_id  customer_id  order_date  order_amount currency
0      1001          103  2025-10-11        125.01      USD
1      1002           93  2025-02-24        287.89      USD
2      1003           15  2025-07-05        213.84      USD
3      1004          107  2025-09-01         51.15      USD
4      1005           72  2025-02-05        141.88      USD

##### *Shipments Table*

In [9]:
status = []
status_choices = ["SHIPPED", "IN_TRANSIT", "DELIVERED"]

In [11]:
for order_id, order_date in zip(orders["order_id"], orders["order_date"]):
    shipped_at = order_date + timedelta(days=np.random.randint(1, 5))

    order_status = np.random.choice(status_choices, p=[0.2, 0.3, 0.5])

    delivered_at = (
        shipped_at + timedelta(days=np.random.randint(1, 7))
        if order_status == "DELIVERED"
        else pd.NaT
    )

    status.append({
        "shipment_id": fake.uuid4(),
        "order_id": order_id,
        "status": order_status,
        "shipped_at": shipped_at,
        "delivered_at": delivered_at
    })

shipments = pd.DataFrame(status)

In [34]:
shipments.head()

,shipment_id,order_id,status,shipped_at,delivered_at
0,6356d526-dfa8-4182-bddc-792959bec865,1001,IN_TRANSIT,2025-10-14,NaT
1,9be5f11e-cf34-46ae-ba90-682737818691,1002,DELIVERED,2025-02-27,2025-03-05
2,5947d0e7-7a2a-493a-89f5-c18c7662ef21,1003,DELIVERED,2025-07-07,2025-07-08
3,f4456709-09b3-4d0b-9e09-021e7bc5946f,1004,SHIPPED,2025-09-05,NaT
4,9087486e-c3b8-4eb1-b59d-040d731a49ba,1005,IN_TRANSIT,2025-02-08,NaT

In [35]:
customers.to_csv("customers.csv", index=False)
orders.to_csv("orders.csv", index=False)
shipments.to_csv("shipment.csv", index=False)